spring:
  application:
    name: order-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
#  boot:
#    admin:
#      client:
#        url: http://localhost:8070

server:
  port: 8083