spring:
  application:
    name: product-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/product}
    username: ${SPRING_DATASOURCE_USERNAME:sadok}
    password: ${SPRING_DATASOURCE_PASSWORD:sadok}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

server:
  port: 8081