spring:
  application:
    name: config-server
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
server:
  port: 8070


